python xgboostGblinear.py data/train-geo data/test-geo result/geo.model > result/geo.result
python xgboostGblinear.py data/train-brand data/test-brand result/brand.model > result/brand.result
python xgboostGblinear.py data/train-os data/test-os result/os.model > result/os.result
python xgboostGblinear.py data/train-session_count data/test-session_count result/session_count.model > result/session_count.result
python xgboostGblinear.py data/train-appid data/test-appid result/appid.model > result/appid.result
python xgboostGblinear.py data/train-geo.brand data/test-geo.brand result/geo.brand.model > result/geo.brand.result
python xgboostGblinear.py data/train-geo.os data/test-geo.os result/geo.os.model > result/geo.os.result
python xgboostGblinear.py data/train-geo.session_count data/test-geo.session_count result/geo.session_count.model > result/geo.session_count.result
python xgboostGblinear.py data/train-geo.appid data/test-geo.appid result/geo.appid.model > result/geo.appid.result
python xgboostGblinear.py data/train-brand.os data/test-brand.os result/brand.os.model > result/brand.os.result
python xgboostGblinear.py data/train-brand.session_count data/test-brand.session_count result/brand.session_count.model > result/brand.session_count.result
python xgboostGblinear.py data/train-brand.appid data/test-brand.appid result/brand.appid.model > result/brand.appid.result
python xgboostGblinear.py data/train-os.session_count data/test-os.session_count result/os.session_count.model > result/os.session_count.result
python xgboostGblinear.py data/train-os.appid data/test-os.appid result/os.appid.model > result/os.appid.result
python xgboostGblinear.py data/train-session_count.appid data/test-session_count.appid result/session_count.appid.model > result/session_count.appid.result
python xgboostGblinear.py data/train-geo.brand.os data/test-geo.brand.os result/geo.brand.os.model > result/geo.brand.os.result
python xgboostGblinear.py data/train-geo.brand.session_count data/test-geo.brand.session_count result/geo.brand.session_count.model > result/geo.brand.session_count.result
python xgboostGblinear.py data/train-geo.brand.appid data/test-geo.brand.appid result/geo.brand.appid.model > result/geo.brand.appid.result
python xgboostGblinear.py data/train-geo.os.session_count data/test-geo.os.session_count result/geo.os.session_count.model > result/geo.os.session_count.result
python xgboostGblinear.py data/train-geo.os.appid data/test-geo.os.appid result/geo.os.appid.model > result/geo.os.appid.result
python xgboostGblinear.py data/train-geo.session_count.appid data/test-geo.session_count.appid result/geo.session_count.appid.model > result/geo.session_count.appid.result
python xgboostGblinear.py data/train-brand.os.session_count data/test-brand.os.session_count result/brand.os.session_count.model > result/brand.os.session_count.result
python xgboostGblinear.py data/train-brand.os.appid data/test-brand.os.appid result/brand.os.appid.model > result/brand.os.appid.result
python xgboostGblinear.py data/train-brand.session_count.appid data/test-brand.session_count.appid result/brand.session_count.appid.model > result/brand.session_count.appid.result
python xgboostGblinear.py data/train-os.session_count.appid data/test-os.session_count.appid result/os.session_count.appid.model > result/os.session_count.appid.result
python xgboostGblinear.py data/train-geo.brand.os.session_count data/test-geo.brand.os.session_count result/geo.brand.os.session_count.model > result/geo.brand.os.session_count.result
python xgboostGblinear.py data/train-geo.brand.os.appid data/test-geo.brand.os.appid result/geo.brand.os.appid.model > result/geo.brand.os.appid.result
python xgboostGblinear.py data/train-geo.brand.session_count.appid data/test-geo.brand.session_count.appid result/geo.brand.session_count.appid.model > result/geo.brand.session_count.appid.result
python xgboostGblinear.py data/train-geo.os.session_count.appid data/test-geo.os.session_count.appid result/geo.os.session_count.appid.model > result/geo.os.session_count.appid.result
python xgboostGblinear.py data/train-brand.os.session_count.appid data/test-brand.os.session_count.appid result/brand.os.session_count.appid.model > result/brand.os.session_count.appid.result
python xgboostGblinear.py data/train-geo.brand.os.session_count.appid data/test-geo.brand.os.session_count.appid result/geo.brand.os.session_count.appid.model > result/geo.brand.os.session_count.appid.result
